name: random
description: A new Flutter package project.
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  common_dependencies:
    path: ../../core/common_dependencies

  json_annotation: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  assets:
    - assets/random.json